const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  saveTimeline: (data, filename) => ipcRenderer.invoke('save-timeline', { data, filename }),
  listTimelines: () => ipcRenderer.invoke('list-timelines'),
  loadTimeline: (filename) => ipcRenderer.invoke('load-timeline', filename),
  exportTimeline: (data, suggestedName) => ipcRenderer.invoke('export-timeline', { data, suggestedName }),
  importTimeline: () => ipcRenderer.invoke('import-timeline'),
  deleteTimeline: (payload) => ipcRenderer.invoke('delete-timeline', payload),
  createNote: (payload) => ipcRenderer.invoke('create-note', payload),
  addExistingNote: (payload) => ipcRenderer.invoke('add-existing-note', payload),
  readNote: (payload) => ipcRenderer.invoke('read-note', payload),
  writeNote: (payload) => ipcRenderer.invoke('write-note', payload),
  deleteNote: (payload) => ipcRenderer.invoke('delete-note', payload),
  renameNote: (payload) => ipcRenderer.invoke('rename-note', payload),
  renameTimeline: (payload) => ipcRenderer.invoke('rename-timeline', payload),
  getAppSettings: () => ipcRenderer.invoke('get-app-settings'),
  setAppSettings: (settings) => ipcRenderer.invoke('set-app-settings', settings),
  chooseTimelinesDir: () => ipcRenderer.invoke('choose-timelines-dir'),
  chooseNotesDir: () => ipcRenderer.invoke('choose-notes-dir'),
  choosePluginsDir: () => ipcRenderer.invoke('choose-plugins-dir'),
  openPluginsFolder: (payload) => ipcRenderer.invoke('open-plugins-folder', payload),
  listPlugins: (payload) => ipcRenderer.invoke('list-plugins', payload),
  readPluginModule: (payload) => ipcRenderer.invoke('read-plugin-module', payload),
  chooseNotesSubfolder: () => ipcRenderer.invoke('choose-notes-subfolder'),
  relaunchApp: () => ipcRenderer.invoke('relaunch-app'),
  openTimelinesFolder: () => ipcRenderer.invoke('open-timelines-folder'),
  openNotesFolder: () => ipcRenderer.invoke('open-notes-folder'),
  openThemesFolder: () => ipcRenderer.invoke('open-themes-folder'),
  openFontsFolder: () => ipcRenderer.invoke('open-fonts-folder'),
  getNotesBaseDir: () => ipcRenderer.invoke('get-notes-base-dir'),
  listThemes: () => ipcRenderer.invoke('list-themes'),
  listFonts: () => ipcRenderer.invoke('list-fonts'),
  saveUserTheme: (payload) => ipcRenderer.invoke('save-user-theme', payload),
  deleteUserTheme: (payload) => ipcRenderer.invoke('delete-user-theme', payload),
  fetchWikipedia: (payload) => ipcRenderer.invoke('fetch-wikipedia', payload),
  openExternal: (payload) => ipcRenderer.invoke('open-external', payload),
  saveCloudCache: (payload) => ipcRenderer.invoke('save-cloud-cache', payload),
  loadCloudCache: (backendId) => ipcRenderer.invoke('load-cloud-cache', backendId),
  updateCloudMeta: (payload) => ipcRenderer.invoke('update-cloud-meta', payload),
  deleteCloudCache: (backendId) => ipcRenderer.invoke('delete-cloud-cache', backendId),
  listCloudMetas: () => ipcRenderer.invoke('list-cloud-metas'),
  captureScreenshot: () => ipcRenderer.invoke('capture-screenshot'),
  // Window controls
  minimizeWindow: () => ipcRenderer.send('minimize-window'),
  maximizeWindow: () => ipcRenderer.send('maximize-window'),
  closeWindow: () => ipcRenderer.send('close-window'),
  // Auto-updater
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdaterStatus: (callback) => {
    ipcRenderer.on('updater-status', (_event, data) => callback(data));
  },
  offUpdaterStatus: () => {
    ipcRenderer.removeAllListeners('updater-status');
  },
});
