const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  saveTimeline: (data, filename) => ipcRenderer.invoke('save-timeline', { data, filename }),
  listTimelines: () => ipcRenderer.invoke('list-timelines'),
  loadTimeline: (filename) => ipcRenderer.invoke('load-timeline', filename),
  exportTimeline: (data, suggestedName) => ipcRenderer.invoke('export-timeline', { data, suggestedName }),
  importTimeline: () => ipcRenderer.invoke('import-timeline'),
  deleteTimeline: (payload) => ipcRenderer.invoke('delete-timeline', payload),
  createNote: (payload) => ipcRenderer.invoke('create-note', payload),
  addExistingNote: (payload) => ipcRenderer.invoke('add-existing-note', payload),
  readNote: (payload) => ipcRenderer.invoke('read-note', payload),
  writeNote: (payload) => ipcRenderer.invoke('write-note', payload),
  deleteNote: (payload) => ipcRenderer.invoke('delete-note', payload),
  renameNote: (payload) => ipcRenderer.invoke('rename-note', payload),
  renameTimeline: (payload) => ipcRenderer.invoke('rename-timeline', payload),
  getAppSettings: () => ipcRenderer.invoke('get-app-settings'),
  setAppSettings: (settings) => ipcRenderer.invoke('set-app-settings', settings),
  chooseTimelinesDir: () => ipcRenderer.invoke('choose-timelines-dir'),
  chooseNotesDir: () => ipcRenderer.invoke('choose-notes-dir'),
  choosePluginsDir: () => ipcRenderer.invoke('choose-plugins-dir'),
  openPluginsFolder: (payload) => ipcRenderer.invoke('open-plugins-folder', payload),
  listPlugins: (payload) => ipcRenderer.invoke('list-plugins', payload),
  readPluginModule: (payload) => ipcRenderer.invoke('read-plugin-module', payload),
  chooseNotesSubfolder: () => ipcRenderer.invoke('choose-notes-subfolder'),
  openThemesFolder: () => ipcRenderer.invoke('open-themes-folder'),
  openFontsFolder: () => ipcRenderer.invoke('open-fonts-folder'),
  getNotesBaseDir: () => ipcRenderer.invoke('get-notes-base-dir'),
  listThemes: () => ipcRenderer.invoke('list-themes'),
  listFonts: () => ipcRenderer.invoke('list-fonts'),
  saveUserTheme: (payload) => ipcRenderer.invoke('save-user-theme', payload),
  deleteUserTheme: (payload) => ipcRenderer.invoke('delete-user-theme', payload),
  fetchWikipedia: (payload) => ipcRenderer.invoke('fetch-wikipedia', payload),
  openExternal: (payload) => ipcRenderer.invoke('open-external', payload),
  // Window controls
  minimizeWindow: () => ipcRenderer.send('minimize-window'),
  maximizeWindow: () => ipcRenderer.send('maximize-window'),
  closeWindow: () => ipcRenderer.send('close-window'),
});
